[package]
name = "bitcoinsv"
version = "0.2.5"
edition = "2021"
authors = ["Daniel Connolly <daniel@dconnolly.com>"]
repository = "https://github.com/Danconnolly/rust-bitcoinsv"
license-file = "../LICENSE.txt"
readme = "../README.md"
description = "Low-level Bitcoin SV library, focused on infrastructure."
homepage = "https://github.com/Danconnolly/rust-bitcoinsv"
documentation = "https://docs.rs/bitcoinsv/latest/bitcoinsv/"
keywords = ["crypto", "bitcoin-sv"]

[dependencies]
tokio = { version = ">=1.23.1", features = ["full"] }
async-trait = "0.1.75"
tokio-stream = "0.1"
futures = "0.3.30"

byteorder = "1.5.0"
hex = "0.4.3"
log = "0.4.20"
ring = "0.17.7"
serde = { version = "1.0.193", features = ["derive"] }
uuid = { version = "1.3.2", features = ["v4", "fast-rng", "macro-diagnostics"] }

[dev-dependencies]
serde_json = { version = "1.0.108", features = [] }

[lib]
path = "src/lib.rs"

