[package]
name = "bitcoinsv"
version = "0.2.6"
edition = "2021"
authors = ["Daniel Connolly <daniel@dconnolly.com>"]
repository = "https://github.com/Danconnolly/rust-bitcoinsv"
license-file = "../LICENSE.txt"
readme = "../README.md"
description = "Low-level Bitcoin SV library, focused on infrastructure."
homepage = "https://github.com/Danconnolly/rust-bitcoinsv"
documentation = "https://docs.rs/bitcoinsv/latest/bitcoinsv/"
keywords = ["crypto", "bitcoin-sv"]

[dependencies]
async-trait = "0.1.75"
base58 = "0.2.0"
byteorder = "1.5.0"
bytes = "1.7.1"
futures = "0.3.30"
hex = "0.4.3"
log = "0.4.20"
minactor = "0.3.0"
num = "0.4.3"
rand = "0.8.5"
ring = "0.17.7"
ripemd = "0.1.3"
secp256k1 = { version = "0.29.0", features = ["alloc", "rand-std"] }
serde = { version = "1.0.193", features = ["derive"] }
tokio = { version = ">=1.23.1", features = ["full"] }
tokio-stream = "0.1"
tokio-util = "0.7.12"
uuid = { version = "1.3.2", features = ["v4", "fast-rng", "macro-diagnostics"] }

[dev-dependencies]
hex-literal = "0.4.1"
serde_json = { version = "1.0.108", features = [] }

[lib]
path = "src/lib.rs"

