[package]
name = "bitcoinsv"
version = "0.0.1"
edition = "2021"
authors = ["Daniel Connolly <daniel@dconnolly.com>"]
repository = "https://github.com/Danconnolly/rust-bitcoinsv"
license-file = "LICENSE.txt"

[dependencies]
tokio = { version = "1", features = ["full"] }
async-trait = "0.1.75"
uuid = { version = "1.3.2", features = ["v4", "fast-rng", "macro-diagnostics"] }
hex = "0.4.3"
ring = "0.14.6"  # need to maintain compatibility with rust-sv for now
serde = "1.0.193"
futures = "0.3.30"

[dev-dependencies]
serde_json = { version = "1.0.108", features = [] }

[lib]
path = "src/lib.rs"

