name: Property-Based Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]
  workflow_dispatch: # Allow manual trigger

jobs:
  proptest:
    name: Property Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install cargo nextest
        uses: taiki-e/install-action@v2
        with:
          tool: nextest

      - name: Run property-based tests
        run: cargo nextest run --profile proptest --no-fail-fast -E 'test(::proptest_tests::)'
        timeout-minutes: 30
